### ISSUE TITLE
Training errors

### ISSUE THREAD

**Issue by Eric3911** [Adamdad/keras-YOLOv3-mobilenet#22]
Create YOLOv3 model with 9 anchors and 5 classes.
[<tf.Tensor 'conv2d_7/BiasAdd:0' shape=(?, ?, ?, 30) dtype=float32>, <tf.Tensor 'conv2d_15/BiasAdd:0' shape=(?, ?, ?, 30) dtype=float32>, <tf.Tensor 'conv2d_23/BiasAdd:0' shape=(?, ?, ?, 30) dtype=float32>]
Train on 749 samples, val on 0 samples, with batch size 1.
Epoch 1/300
749/749 [==============================] - 276s 368ms/step - loss: 930.2716
Epoch 2/300
749/749 [==============================] - 275s 367ms/step - loss: 75.0715
Epoch 3/300
749/749 [==============================] - 274s 366ms/step - loss: 68.3971
Traceback (most recent call last):
  File "train_Mobilenet.py", line 200, in <module>
    _main()
  File "train_Mobilenet.py", line 75, in _main
    callbacks=[logging, checkpoint])
  File "/home/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 429, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'

**Comment by Zanderzt** [comment]
Hello,I had created this folder,but it reminded the same mistake,had you solved it?
