### ISSUE TITLE
KeyError: 'val_loss'

### ISSUE THREAD

**Issue by MichaelCong** [Adamdad/keras-YOLOv3-mobilenet#52]
Epoch 3/30
306/306 [==============================] - 255s 834ms/step - loss: 35.1770
Traceback (most recent call last):
  File "train_Mobilenet.py", line 200, in <module>
    _main()
  File "train_Mobilenet.py", line 75, in _main
    callbacks=[logging, checkpoint])
  File "/home/rencong/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/rencong/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/rencong/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/rencong/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/rencong/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 429, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'

**Comment by funmonty** [comment]
I also got this error. This was present because the validation set was not given to model.fit(). Initially the following lines would be commented. Just uncomment it to get it working.

https://github.com/Adamdad/keras-YOLOv3-mobilenet/blob/d8ac3e269a6f536341305cd8e618ffac3e1e3c73/train_Mobilenet.py#L53-L57
